apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "ul1IJkkmyKDFDlL7c/tpPryjWVMP5qTYNlGPharVyI8REr4If9MCgdQtyfMcp+R8\nkMg6e8T/8LSOUU/0lGFivJBCOUUBGZ93YcStMd3d53MJF8dx4XNTkTVeISIrTTfB\nKGW9AzaMw1l6xKWocriZ2vXEVtJYCic8x71E6ore0gU="
